version: '3'
services:
  nodeapp:
    image: node:20
    container_name: nodeapp
    working_dir: /app
    volumes:
      - ./app:/app
    ports:
      - "3000:3000"
      - "51204:51204"
    tty: true
    command: bash

  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_DB: apisolid
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
    ports:
      - "5432:5432"

